#ifndef GIT_VERSION_H
#define GIT_VERSION_H

// These variables are autogenerated and compiled
// into the library by the git_version.cmake script
#ifdef __cplusplus
extern "C" {
#endif

extern const char *GIT_TAG;
extern const char *GIT_REV;
extern const char *GIT_BRANCH;

#ifdef __cplusplus
}
#endif

// static inline so that translation units including this header without using
// every accessor do not trip -Wunused-function
static inline const char *git_version(void)
{
    return GIT_TAG;
}

static inline const char *git_revision(void)
{
    return GIT_REV;
}

static inline const char *git_branch(void)
{
    return GIT_BRANCH;
}

#endif // GIT_VERSION_H
