name: Conventional Commits

permissions:
  contents: read
  pull-requests: read # needed to read PR title

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited # re-check when title is updated
      - synchronize # re-check on new commits (in case title was just fixed)
      - reopened

jobs:
  pr-title-lint:
    name: Verify Conventional Commit

    if: (github.event_name == 'pull_request' && !startsWith(github.event.pull_request.head.ref, 'release-please--'))

    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Must match your commitlint type-enum
          types: |
            build
            ci
            chore
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          requireScope: false # set true if you want scope mandatory
          subjectPattern: ^[^A-Z].* # disallow sentence-case start (mirrors your subject-case rule)
          subjectPatternError: |
            Subject must start with a lowercase letter.
